modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="wanderer"
version="${file.jarVersion}"
displayName="Wanderer"
authors="appw"
description='''

'''

[[dependencies.wanderer]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.wanderer]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
